[features]
seeds = false
skip-lint = false
[programs.localnet]
crowd_funding = "8oxeTopUZ53GTyQyaEYi33uwamRGm8KC7QX6ndAgPTLX"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "Devnet"
# wallet = "/home/modnab/.config/solana/id.json"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
